<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-12-13">

<title>Dynamic Documents for Reproducible Research using R and Quarto Intro</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="finches_quarto_script_files/libs/clipboard/clipboard.min.js"></script>
<script src="finches_quarto_script_files/libs/quarto-html/quarto.js"></script>
<script src="finches_quarto_script_files/libs/quarto-html/popper.min.js"></script>
<script src="finches_quarto_script_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="finches_quarto_script_files/libs/quarto-html/anchor.min.js"></script>
<link href="finches_quarto_script_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="finches_quarto_script_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="finches_quarto_script_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="finches_quarto_script_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="finches_quarto_script_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Dynamic Documents for Reproducible Research using R and Quarto Intro</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 13, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Natural selection is a fundamental mechanism of evolutionary change, driving the adaptation of organisms to their environments. In species that are highly adapted to specific environmental conditions, environmental changes can exert strong selective pressures, leading to significant shifts in the population. Darwin’s finches, such as the medium ground finch (<em>Geospiza fortis</em>), provide an exemplary case of how natural selection operates in response to such changes<sup>1,2</sup>. These finches primarily feed on seeds, the availability of which is strongly influenced by climatic conditions, particularly yearly rainfall patterns<sup>3</sup>. Consequently, significant changes in rainfall, such as severe droughts can have significant impacts on finch populations by altering seed availability.</p>
<p>A notable example of this phenomenon is the severe drought of 1977, which had profound effects on the finch population of Daphne Major <sup>4</sup>. Rainfall during the wet season plummeted from 127 mm in 1976 to just 24 mm in 1977, resulting in a sharp decline in seed abundance. This drastic reduction in available food led to an 85% decline in the <em>G. fortis</em> population. This decline was strongly correlated with the scarcity of small seeds, which are typically favored by these birds due to the ease of processing them<sup>4</sup>. As small seeds became less available, the finches were forced to shift their feeding behavior, consuming larger, harder seeds that they would typically avoid due to the high energetic costs associated with breaking them open. This dietary shift would have likely introduced new selection pressures, favoring individuals with beaks capable of handling these tougher seeds. Notably, deeper beaks have been shown to deeper and wider beaks dissipate stress more effectively and reduce peak stress magnitudes, allowing finches to crack hard seeds with reduced risk of beak fracture<sup>5</sup>. Thus, under the conditions of food scarcity brought on by the drought, it is expected that grater beak depths would have provided a selective advantage, enabling the finches to survive and reproduce. As such, we would expect to see an increase in the frequency of depper beaks in the finch population after the drought.</p>
</section>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<p>Given the significant environmental changes caused by the drought of 1977, I hypothesise that by comparing populations of <em>G. fortis</em> finches from before and after the drought, notable differences will be observed in their beak depths. Specifically, I expect that the finches measured after the drought, will exhibit greater beak depths when compared to those measured before the drought.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>To investigate the differences in beak morphology across <em>G. fortis</em> finches, I will be utilizing the case0201 dataset from the Sleuth3 package, a simplified subset of a long-term study conducted by Peter and Rosemary Grant in the 1980s<sup>3</sup>. Their study focused on the medium ground finch (<em>G. fortis</em>) on the Galápagos Island of Daphne Major from 1975 to 1978. Over this period, the Grants banded and measured all the finches across more than 20 generations, collecting data on several external morphological characters as well as many environmental parameters. Specifically, the case0201 dataset includes beak depth measurements for 89 finches caught in 1976 (the year before the drought) and 89 finches caught in 1978 (the year after the drought). This data will enable me to assess whether the severe drought of 1977 could have caused changes in beak morphology, in particular increases in beak depth, in response to the environmental pressures it imposed.</p>
</section>
<section id="statistical-analyses" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analyses">Statistical analyses</h3>
<p>To investigate the effect of the 1977 drought on the beak depth of <em>G. fortis</em> finches, I will perform a linear model analysis. This model will allow us to examine how beak depth differs between the two groups (1976 and 1978), with year as the independent variable. By fitting this model, we will obtain both point estimates and confidence intervals for the effect of year on beak depth, providing insight into the drought’s potential influence on finch beak morphology.</p>
<p>Notably, the linear model relies on certain assumptions, including homoscedasticity (constant variance of residuals) and the normality of residuals.</p>
<p>To assess these assumptions, I will first visually inspect diagnostic plots:</p>
<ul>
<li><p>A Residuals vs.&nbsp;Fitted plot will be used to assess homoscedasticity, which assumes that the variance of residuals is constant across all levels of the fitted values. A random scatter of points around zero (no discernible pattern) would suggests that the homoscedasticity assumption is met.</p></li>
<li><p>A Normal Q-Q plot will be used to evaluate whether the residuals follow a normal distribution. If the residuals are normally distributed, the points would closely follow the diagonal line in the plot.</p></li>
</ul>
<p>I will also conduct formal statistical tests:</p>
<ul>
<li><p>A Levene’s test will be used to test the assumption of homoscedasticity. This test evaluates whether the variance of the residuals is constant across groups.</p></li>
<li><p>A Shapiro-Wilk test will be applied to assess the normality of the residuals. A significant result (p-value &lt; 0.05) would suggest that the residuals are not normally distributed.</p></li>
</ul>
<p>By evaluating these assumptions, I aim to strengthen the reliability and interpretability of the analysis, ensuring transparency in assessing the appropriateness of the statistical methods used.</p>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<p><em>Important note: Comprehensive instructions, including all prerequisites and detailed guidelines for running this analysis and relevant code, are available in the README file of my <a href="https://github.com/Biology3579/FinchesAssignmentProject.git">GitHub repository</a> for this project. Please refer to the README to ensure proper setup and usage.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>renv<span class="sc">::</span><span class="fu">restore</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- The library is already synchronized with the lockfile.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Source library loading fucntion</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"functions"</span>, <span class="st">"libraries.R"</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">load_libraries</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-handling" class="level3">
<h3 class="anchored" data-anchor-id="data-handling">Data handling</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Load the raw data and save it</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(case0201, <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"finches_raw.csv"</span>))    <span class="co">#To write data to csv</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>finches_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>,<span class="st">"finches_raw.csv"</span>)) <span class="co">#Load data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick look at the case0201 dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(finches_raw) <span class="co"># Outputs first few rows of the dataset </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X Year Depth
1 1 1976   6.2
2 2 1976   6.8
3 3 1976   7.1
4 4 1976   7.1
5 5 1976   7.4
6 6 1976   7.8</code></pre>
</div>
</div>
<p>After reviewing the raw data, it was important to clean it to improve accessibility and facilitate the analysis process. For a detailed description of the cleaning functions, refer to the <code>cleaning.R</code> file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Source the cleaning function</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"functions"</span>, <span class="st">"cleaning.R"</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply cleaning function</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>finches_clean <span class="ot">&lt;-</span> <span class="fu">cleaning_data</span>(finches_raw)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the clean data</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(finches_clean, <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"finches_clean.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-analysis">Exploratory analysis</h3>
<p>Before proceeding with statistical modeling, it is useful to conduct a preliminary visual examination of the data to assess the variation within each group and between the two years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Source the plotting functions</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"functions"</span>, <span class="st">"plotting.R"</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply plot function</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>exploratory_boxplot <span class="ot">&lt;-</span> <span class="fu">plot_exploratory_boxplot</span>(finches_clean)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppress the null device output</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">capture.output</span>(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply save function</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">save_plot_svg</span>(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    finches_clean,                           <span class="co"># Data</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figures/exploratory_boxplot.svg"</span>,       <span class="co"># Filename (and path: folder/name)</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">15</span>,                               <span class="co"># Sizing</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">scaling =</span> <span class="dv">1</span>,                             <span class="co"># Scaling</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot_function =</span> plot_exploratory_boxplot)<span class="co"># Plot function</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>exploratory_boxplot <span class="co"># Show plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="finches_quarto_script_files/figure-html/exploratory-boxplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 1: Boxplot comparing the distribution of finches beak depths in 1976 and 1978.</em></p>
<p>The distribution of beak depth in finches before (1976) and after (1978) the drought is shown in Figure 1. The data suggest a potential shift in the population’s beak depth, as the median beak depth in 1978 appears to be higher than in 1976. However, the plot also reveals substantial variation within both years, with considerable overlap in the interquartile ranges. While this exploratory analysis highlights a possible change in beak depth, it does not provide evidence for statistical significance. To assess whether the observed differences are meaningful, formal statistical tests are required.</p>
</section>
<section id="statistical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis">Statistical analysis</h3>
<p>A linear model is be employed to evaluate the effect of the drought on beak depth. In this model, “year” is treated as the explanatory variable, while “beak_depth_mm” is the response variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a linear model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>linear_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(beak_depth_mm <span class="sc">~</span> year, <span class="at">data =</span> finches_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="checking-model-assumptions" class="level4">
<h4 class="anchored" data-anchor-id="checking-model-assumptions">Checking model assumptions</h4>
</section>
<section id="diagnostic-plots" class="level4">
<h4 class="anchored" data-anchor-id="diagnostic-plots">Diagnostic plots</h4>
<p>To assess the assumptions of the linear model, diagnostic plots were generated to evaluate both homoscedasticity and normality of the residuals.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Source the plotting functions</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"functions"</span>, <span class="st">"plotting.R"</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply plot function</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>diagnostic_plots <span class="ot">&lt;-</span> <span class="fu">plot_diagnostics</span>(linear_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="finches_quarto_script_files/figure-html/diagnostic-plots-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppress the null device output</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">capture.output</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply save function</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">save_plot_svg</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    finches_clean, </span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figures/exploratory_boxplot.svg"</span>, </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">15</span>, </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">scaling =</span> <span class="dv">1</span>, </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot_function =</span> plot_diagnostics)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Figure 2: Diagnostic plots for assessing model assumptions. On the left panel, the Residuals vs Fitted plot assesses homoscedasticity (constant variance of the residuals). The right panel displays a Normal Q-Q plot, which is used to assess the normality of the residuals.</em></p>
<p>The Residuals vs Fitted plot in Figure 2 indicates that the assumption of homoscedasticity is likely met. The spread of residuals appears relatively consistent across both years (1976 and 1978), with both groups showing comparable levels of divergence from the fitted line. This suggests that the variance of residuals is similar for the two groups, supporting the assumption that the residuals have constant variance across the data. The lack of a clear pattern or systematic trend in the plot further reinforces this conclusion. In contrast, the Normal Q-Q plot shows a mild departure from the normality assumption. The residuals deviate from the expected normal distribution, particularly at the extremes (the tails of the distribution). This deviation may affect the validity of statistical inference, such as the calculation of confidence intervals and significance tests.</p>
<p>To formally evaluate these assumptions, additional statistical tests are necessary.</p>
</section>
<section id="testing-homogeneity-of-variance" class="level4">
<h4 class="anchored" data-anchor-id="testing-homogeneity-of-variance">Testing homogeneity of variance</h4>
<p>A Levene’s test was conducted to formally test the homogeneity of variance in beak depths between the two finch populations</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Levene's test </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>levene_test <span class="ot">&lt;-</span> <span class="fu">leveneTest</span>(linear_model)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>levene_test <span class="co"># Display results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)
group   1   1.361 0.2449
      176               </code></pre>
</div>
</div>
<p>The non-significant p-value (p = 0.2449 &gt;&gt; 0.05) indicates that there is no evidence to reject the null hypothesis of equal variances in beak depth measurements between the two populations of finches. This result, combined with the Residuals vs.&nbsp;Fitted plot, which equally seems to show that both groups have a similar spread of residuals around the central line, suggests that the assumption of homoscedasticity is satisfied.</p>
</section>
<section id="tetsing-normality-of-residuals" class="level4">
<h4 class="anchored" data-anchor-id="tetsing-normality-of-residuals">Tetsing normality of residuals</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the Shapiro-Wilk test </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(<span class="fu">resid</span>(linear_model))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>shapiro_test <span class="co"># Display results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  resid(linear_model)
W = 0.97012, p-value = 0.0007184</code></pre>
</div>
</div>
<p>The statistically significant p-value (p = 0.0007184 &lt;&lt; 0.05) indicates a departure from normality in the distribution of beak depth values. This result aligns with the deviations observed in the Normal Q-Q plot, where the data exhibited some deviation from the expected distribution at the extremes.</p>
<p>While the violation of normality should be noted, the central limit theorem implies that, despite non-normality, the model’s estimates could remain reliable. It is important to acknowledge that the violation of normality can influence the precision of predictions, especially in smaller samples, but in this case, the large dataset likely mitigates these concerns. Therefore, while the normality assumption is not fully satisfied, the analysis remains robust, and the conclusions drawn from the linear model are likely valid.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Source the plotting functions</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"functions"</span>, <span class="st">"plotting.R"</span>))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply plot fucntion</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> <span class="fu">generate_summary_table</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  linear_model,                   <span class="co"># The linear model to summarize</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">term_label =</span> <span class="st">"1976 vs 1978"</span>,    <span class="co"># Label for the term being compared (years 1976 and 1978)</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">effect_size_label =</span> <span class="st">"Estimate"</span>, <span class="co"># Custom label for effect size (e.g., the regression coefficient)</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value_label =</span> <span class="st">"p-value"</span>,      <span class="co"># Custom label for the p-value from the model output</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf_lower_label =</span> <span class="st">"Lower CI"</span>,  <span class="co"># Custom label for the lower bound of the confidence interval</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf_upper_label =</span> <span class="st">"Upper CI"</span>   <span class="co"># Custom label for the upper bound of the confidence interval</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the table</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  Year_Effect  Estimate `p-value` `Lower CI` `Upper CI`
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
1 1976 vs 1978    0.669         0      0.381      0.956</code></pre>
</div>
</div>
<p><em>Table 1: Summary of the linear model for the effect of year (1976 vs.&nbsp;1978) on beak depth. The table shows the effect size (estimate), the p-value, and the confidence interval (95% CI) for the year variable.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Source the plotting functions</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"functions"</span>, <span class="st">"plotting.R"</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply plot function</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>results_boxplot <span class="ot">&lt;-</span> <span class="fu">plot_results_boxplot</span>(finches_clean)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppress the null device output</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">capture.output</span>(</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply save function</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">save_plot_svg</span>(</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    finches_clean, </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figures/results_boxplot.svg"</span>, </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">15</span>, </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">scaling =</span> <span class="dv">1</span>, </span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot_function =</span> plot_results_boxplot)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>results_boxplot <span class="co"># Show plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="finches_quarto_script_files/figure-html/plot-results-boxplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 3: Boxplot illustrating the differences in beak depth between 1976 and 1978. Statistical significance between the two years is denoted by asterisks (* p &lt; 0.001)</em></p>
<p>The linear model analysis explored the effect of year (1976 vs.&nbsp;1978) on beak depth in <em>G. fortis</em> finches, specifically testing the hypothesis that significant environmental changes, particularly the 1977 drought, could have caused changes in beak morphology. The results, as summarized in Table 1, provide compelling evidence that beak depth increased significantly in 1978 compared to 1976 (p &lt; 0.001), confirming the hypothesis that the drought may have exerted a selective pressure favoring finches with larger beaks. This shift in beak morphology is visually illustrated in Figure 3, which compares the beak depths of finches in the two years. The boxplot clearly shows a marked increase in the mean beak depth in 1978, reinforcing the conclusion that notable differences are observed in beak depth across these two populations. The estimated effect size for the difference in beak depth between 1976 and 1978 is 0.6685 mm, meaning that the average beak depth in 1978 was approximately 0.6685 mm larger than in 1976. This effect size is both statistically significant and biologically meaningful, with the 95% confidence interval ranging from 0.381 mm to 0.956 mm.</p>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>The analysis of beak depth in <em>G. fortis</em> finches before and after the 1977 drought provides compelling evidence for natural selection acting on morphological traits in response to environmental pressures. The observed increase in beak depth by 1978 supports the hypothesis that the drought, which reduced small seed availability and increased the reliance on tougher, larger seeds, conferred a selective advantage to finches with deeper beaks. These adaptations likely enhanced the survival and reproductive success of individuals capable of efficiently cracking the harder seeds that dominated the post-drought landscape.</p>
<p>The estimated increase of 0.6685 mm in beak depth, though seemingly small, is both statistically significant and biologically relevant in that even small differences in beak morphology can have profound biomechanical implications. Indeed slight increases in beak depth can significantly enhance the forces a bird can exert when cracking seeds, reducing stress magnitudes and minimizing fracture risks<sup>5</sup>. These advantages may have been critical for accessing and processing harder seeds, which may have resulted in the difference between survival and starvation in post-drought, resource-limited environments.</p>
<p>While the analysis provides robust evidence for natural selection influencing beak morphology in <em>G. fortis</em>, it is constrained by several methodological limitations. Although the sample size is extensive, the focus on a single morphological trait—beak depth—limits the scope of inference. Beak morphology is multifaceted, with traits such as beak width also playing a critical role in seed-cracking efficiency. Beak width, in particular, has been shown to affect biomechanical properties by dissipating stress and reducing the risk of structural failure during feeding<sup>5</sup>. Including such measures in future studies could offer a more comprehensive understanding of the relationship between morphology and function. Additionally, the analysis is based solely on “year” as a categorical factor, without direct inclusion of environmental variables such as seed availability, seed hardness, or climatic conditions like precipitation. These variables are crucial for understanding the selective pressures driving morphological changes. Without this data, conclusions about the drivers of selection remain inferential. Instead, incorporating ecological and climatic data in future studies would allow for regression analyses, potentially identifying direct correlations between environmental changes and morphological adaptations. Finally, the temporal scope of the study, limited to two years, restricts our ability to assess whether observed changes represent enduring evolutionary shifts or transient responses to acute environmental stressors. Longitudinal studies spanning multiple generations, coupled with genetic analyses, are necessary to evaluate the persistence of these changes and to elucidate the genetic and phenotypic mechanisms underlying adaptation.</p>
<p>In conclusion, while the data is partially consistent with natural selection acting on beak depth in <em>G. fortis</em> in response to the 1977 drought, the evidence is not definitive. The observed increase in beak depth suggests an adaptive response to changes in seed availability, however, the available data restricts the ability to fully correlate these morphological changes with the selective pressures imposed by the drought. Additional research is needed to robustly link ecological changes to evolutionary outcomes in this system.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li><sup>1</sup> Boag, P.T. and Grant, P.R. (1981). Intense Natural Selection in a Population of Darwin’s Finches (Geospizinae) in the Galapagos. Science, 214(4516), pp.82–85.</li>
<li><sup>2</sup> Price, T.D., Grant, P.R., Gibbs, H.L. and Boag, P.T. (1984). Recurrent patterns of natural selection in a population of Darwin’s finches. Nature, 309(5971), pp.787–789. doi:https://doi.org/10.1038/309787a0.</li>
<li><sup>3</sup> GRANT, P.R. (1986). Ecology and Evolution of Darwin’s Finches (Princeton Science Library Edition). REVRevised ed.&nbsp;[online] Princeton University Press. doi:https://doi.org/10.2307/j.ctt1m3nz91.</li>
<li><sup>4</sup> Grant, B.R. and Grant, P.R. (1989). Natural Selection in a Population of Darwin’s Finches. The American Naturalist, 133(3), pp.377–393. doi:https://doi.org/10.1086/284924.</li>
<li><sup>5</sup> Soons, J., Herrel, A., Genbrugge, A., Aerts, P., Podos, J., Adriaens, D., de Witte, Y., Jacobs, P. and Dirckx, J. (2010). Mechanical stress, fracture risk and beak evolution in Darwin’s ground finches (Geospiza). Philosophical Transactions of the Royal Society B: Biological Sciences, 365(1543), pp.1093–1098. doi:https://doi.org/10.1098/rstb.2009.0280.</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>